// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.27.1
// source: proto/category/category.proto

package category

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryRequest) Reset() {
	*x = GetCategoryRequest{}
	mi := &file_proto_category_category_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryRequest) ProtoMessage() {}

func (x *GetCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_category_category_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_category_category_proto_rawDescGZIP(), []int{0}
}

func (x *GetCategoryRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Budget        float32                `protobuf:"fixed32,4,opt,name=budget,proto3" json:"budget,omitempty"`
	Ownerid       uint32                 `protobuf:"varint,5,opt,name=ownerid,proto3" json:"ownerid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryResponse) Reset() {
	*x = CategoryResponse{}
	mi := &file_proto_category_category_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryResponse) ProtoMessage() {}

func (x *CategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_category_category_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryResponse.ProtoReflect.Descriptor instead.
func (*CategoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_category_category_proto_rawDescGZIP(), []int{1}
}

func (x *CategoryResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CategoryResponse) GetBudget() float32 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *CategoryResponse) GetOwnerid() uint32 {
	if x != nil {
		return x.Ownerid
	}
	return 0
}

var File_proto_category_category_proto protoreflect.FileDescriptor

const file_proto_category_category_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/category/category.proto\x12\bcategory\"$\n" +
	"\x12GetCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"|\n" +
	"\x10CategoryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06budget\x18\x04 \x01(\x02R\x06budget\x12\x18\n" +
	"\aownerid\x18\x05 \x01(\rR\aownerid2^\n" +
	"\x0fCategoryService\x12K\n" +
	"\x0fGetCategoryByID\x12\x1c.category.GetCategoryRequest\x1a\x1a.category.CategoryResponseB\x10Z\x0eproto/categoryb\x06proto3"

var (
	file_proto_category_category_proto_rawDescOnce sync.Once
	file_proto_category_category_proto_rawDescData []byte
)

func file_proto_category_category_proto_rawDescGZIP() []byte {
	file_proto_category_category_proto_rawDescOnce.Do(func() {
		file_proto_category_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_category_category_proto_rawDesc), len(file_proto_category_category_proto_rawDesc)))
	})
	return file_proto_category_category_proto_rawDescData
}

var file_proto_category_category_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_category_category_proto_goTypes = []any{
	(*GetCategoryRequest)(nil), // 0: category.GetCategoryRequest
	(*CategoryResponse)(nil),   // 1: category.CategoryResponse
}
var file_proto_category_category_proto_depIdxs = []int32{
	0, // 0: category.CategoryService.GetCategoryByID:input_type -> category.GetCategoryRequest
	1, // 1: category.CategoryService.GetCategoryByID:output_type -> category.CategoryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_category_category_proto_init() }
func file_proto_category_category_proto_init() {
	if File_proto_category_category_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_category_category_proto_rawDesc), len(file_proto_category_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_category_category_proto_goTypes,
		DependencyIndexes: file_proto_category_category_proto_depIdxs,
		MessageInfos:      file_proto_category_category_proto_msgTypes,
	}.Build()
	File_proto_category_category_proto = out.File
	file_proto_category_category_proto_goTypes = nil
	file_proto_category_category_proto_depIdxs = nil
}
